export const GET_MOVIES_STARTED = 'GET_MOVIES_STARTED';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';

export const ADD_NOMINATION_STARTED = 'ADD_NOMINATION_STARTED';
export const ADD_NOMINATION_FAILURE = 'ADD_NOMINATION_FAILURE';
export const ADD_NOMINATION_SUCCESS = 'ADD_NOMINATION_SUCCESS';
export const REMOVE_NOMINATION = 'REMOVE_NOMINATION';
export const COMPLETED_NOMINATIONS = 'COMPLETED_NOMINATIONS';
export const CLEAR_NOMINATIONS = 'CLEAR_NOMINATIONS';
export const SAVE_NOMINATIONS = 'SAVE_NOMINATIONS';
