export const GET_MOVIES_STARTED = 'GET_MOVIES_STARTED';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

export const ADD_NOMINATION = 'ADD_NOMINATION';
export const REMOVE_NOMINATION = 'REMOVE_NOMINATION';
